# For technical details of the configuration file, please check comments and sample configurations in file /config.yml.
#
status: "under development"
php:
  - "7.2.34"
  - "7.3.28"
  - "7.4.19"
  - "8.0.6"
image:
  composer:
    version: "2.0.13"
