name: Build Versioned Fpm Alpine Images

on:
  push:
    branches:
      - '[4-9].[0-9]+.[0-9]+'
      - '[4-9].[0-9]+.[0-9]+-?[a-zA-Z]**'

jobs:
  build_versioned_alpine_images:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'lufei/docker-swoole' }}
    strategy:
      fail-fast: true
      matrix:
        php: ["7.1", "7.2", "7.3", "7.4", "8.0"]
        swoole44:
          - ${{ contains(github.ref, '4.4.') }}
        swoole46:
          - ${{ contains(github.ref, '4.6.') }}
        exclude:
          - php: "8.0"
            swoole44: true
          - php: "7.1"
            swoole46: true

    name: The Alpine image for PHP ${{ matrix.php }}

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Set output parameters
        id: params
        run: |
          echo ::set-output name=branch_name::${GITHUB_REF##*/}
          branch_name=${GITHUB_REF##*/}
          major_version=${branch_name%.*}
          if egrep -q '^status\:\s*"under development"\s*($|\#)' "$(pwd)/config/${branch_name}.yml" ; then
            if [ ${{ matrix.php }} == '8.0' ] ; then
              echo "::set-output name=full_names::swooleinc/swoole:${branch_name}-php${{ matrix.php }}-fpm-alpine,swooleinc/swoole:${major_version}-php${{ matrix.php }}-fpm-alpine,swooleinc/swoole:${major_version}-fpm-alpine,swooleinc/swoole:latest-fpm-alpine"
            else
              if [ ${{ matrix.php }} == '7.4' ] && [ ${major_version} == '4.4' ] ; then
                echo "::set-output name=full_names::swooleinc/swoole:${branch_name}-php${{ matrix.php }}-fpm-alpine,swooleinc/swoole:${major_version}-php${{ matrix.php }}-fpm-alpine,swooleinc/swoole:${major_version}-fpm-alpine"
              else
                echo "::set-output name=full_names::swooleinc/swoole:${branch_name}-php${{ matrix.php }}-fpm-alpine,swooleinc/swoole:${major_version}-php${{ matrix.php }}-fpm-alpine"
              fi
            fi
          else
              echo "::set-output name=full_names::swooleinc/swoole:${branch_name}-php${{ matrix.php }}-fpm-alpine"
          fi

      -
        name: Build and push Docker image swooleinc/swoole:${{ steps.params.outputs.branch_name }}-php${{ matrix.php }}-fpm-alpine
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfiles/${{ steps.params.outputs.branch_name }}/php${{ matrix.php }}/fpm-alpine/Dockerfile
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le
          push: true
          tags: ${{ steps.params.outputs.full_names }}

      -
        name: Image digest of swooleinc/swoole:${{ steps.params.outputs.branch_name }}-php${{ matrix.php }}-fpm-alpine
        run: echo ${{ steps.docker_build.outputs.digest }}
